### PR TITLE
Optional Build Targets

### PR DESCRIPTION
**Pull request by fwinnen**
Added Options to skip building some targets.
This is needed for cross compilations on iOS and Android and 
speeds up build time greatly.

Default build is unchanged to enable backward compatibility.

### CODE REVIEW

**Comment by ruslo** [comment]
This is not related to Hunter directly, I think you should send this to [upstream](https://github.com/google/protobuf) first.

**Comment by fwinnen** [comment]
Hmm, thought that i push it here since its based on the hunter build, which is not upstream either.

Should I rebase this on google/protobuf/master then, without the hunter files and after that merge the upstream into hunter-packages/protobuf/hunter? 

I think the goal should be to have both (hunterized and optional builds) upstream eventually...

**Comment by ruslo** [comment]
Final goal is to have only trivial changes in `hunter` branch. I will write explanation in documentation and send the link.

**Comment by ruslo** [comment]
> I will write explanation in documentation and send the link

See https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html

> I think the goal should be to have both (hunterized and optional builds) upstream eventually

Yes

> i push it here since its based on the hunter build, which is not upstream either

I'm not sure about details, if it is so I'm okay about merge. @hunter-packages/protobuf any objections?

**Comment by fwinnen** [comment]
Thank you for the merge :)

If i find some time, I will make a pull request for the optional build without hunter upstream.

**Pull request merged**
