### PR TITLE
Hunterize v3.0.0

### PR DESCRIPTION
**Pull request by Osse**
This ended up being a huge PR so I don't think this is the best way of doing it. But in any case in my fork you will find a tag named `v3.0.0-hunter-1`. I created this by looking at the changes between `v3.0.0-beta-2` and `v3.0.0-beta-2-hunter-2` and making the equivalent changes on top of the `v3.0.0` tag.

### CODE REVIEW

**Comment by ruslo** [comment]
> I created this by looking at the changes between v3.0.0-beta-2 and v3.0.0-beta-2-hunter-2 and making the equivalent changes on top of the v3.0.0 tag

Have you tried `git merge`?

> I don't think this is the best way of doing it

Fork branches should match upstream, so `hunterized/master` to `upstream/master` must be always merged by `git merge --ff-only`. Patches should go to `hunter` branch. As a result both `git diff master..hunter` and `git log master..hunter` will contain only Hunter related changes.

**Comment by Osse** [comment]
I agree. But the hunter branch in this repo does not contain the hunter-related changes at all. `git log hunterized/master..hunterized/hunter` is empty, and in fact `hunterized/hunter` is _behind_ `hunterized/master`, which in turn is behind `upstream/master`. The changes that make up the "hunterization" of v3.0.0-beta-2 are found with `git log hunterized/master..hunterized/v3.0.0-beta-2-hunter`.

I suspect the branch `hunterized/v3.0.0-beta-2-hunter` is what `hunterized/hunter` should have been. The tip of `hunterized/v3.0.0-beta-2-hunter` is tagged `v3.0.0-beta-2-hunter-2`.

`osse/master` is equal to `upstream/master`. and there is only one commit in the range `osse/master..osse/hunter`, which is where I do the necessary changes to make it Hunter-compatible. I could have called this branch `osse/v3.0.0-hunter` which fits how it was done for beta 2, but does not fit how you say it should be.

**Comment by ruslo** [comment]
> But the hunter branch in this repo does not contain the hunter-related changes at all

This is how things **should** look like :) @tatraian can you consult us with the current state?

> I could have called this branch osse/v3.0.0-hunter which fits how it was done for beta 2, but does not fit how you say it should be

It should fit upstream. Is v3.0.0 a separate branch or just a tag from branch master?

**Comment by Osse** [comment]
The upstream tag `v3.0.0` is on the upstream master branch.

In this fork there is a _branch_ named `v3.0.0-beta-2-hunter` containing Hunter-related changes. The tip of this branch has the _tag_ `v3.0.0-beta-2-hunter-2`. Earlier on that branch is also the tag `v3.0.0-beta-2-hunter-1`.

**Comment by ruslo** [comment]
@Osse okay, can you please do `master` -> `master` pull and create branch `hunter` starting from upstream release tag. You have permissions now.

**Comment by Osse** [comment]
Thanks for having faith in me :)

I have made it so that the master branches are equal. And also pushed my hunterization of 3.0.0 and tested it. But before I push , I have a question: @tatraian added the `Protobuf::` namespace. Since beta2 Google have added a namespace themselves, but it is `protobuf::` with lowercase P.  Using the lowercase follows upstream, but requires everyone to modify their code. What do you think?

**Comment by Osse** [comment]
It says it's closed but it isn't. I force-pushed it away (sorry). I am also waiting for an answer to this question before making things final: https://github.com/google/protobuf/issues/1931

**Comment by ruslo** [comment]
> Since beta2 Google have added a namespace themselves, but it is protobuf:: with lowercase P. Using the lowercase follows upstream, but requires everyone to modify their code. What do you think?

Follow upstream. This is one more reason to push non-Hunterized patches upstream instead of keeping them in fork. Just don't forget to edit wiki page.

> It says it's closed but it isn't

What is closed, this pull request? I think since you pushed that code to branch manually GitHub is smart enough to figure out that changes from this pull request already merged.

**Comment by Osse** [comment]
Ok, I will stick to upstream as close as possible.

This is what the hunterization looks like so far: https://github.com/hunter-packages/protobuf/compare/hunter...Osse:hunter

Summary: I use the most recent Hunter and Huntergate , cherry-pick a bunch of fixes to the CMake files since 3.0.0, and change `ZLIB::ZLIB` into `ZLIB::zlib`. I am still not happy as I am waiting for a response on the issue I linked to above, but with that variable set everything works just like it should.

I must admit my original pull request did a lot of stuff wrong. Also I think the CMake setup they have upstream is a bit strange, but I'm a novice.

**Comment by tatraian** [comment]
Sorry Guys, I was out. I planed to update this repo as follows:
You get the original repo. Push all changes to hunterized repo.
Create new hunter branch for the wished release.
Cherry pick the modification from the previous hunter branch. There is only 4-5 commits that modifies only CMake related files.
I guess that is more simple.

**Comment by ruslo** [comment]
@tatraian sounds pretty similar to what we are trying to do as far as I understand. Probably except cherry-picking, since tags created in upstream branch `master` we can pull it until tag commit and do merge into `hunter`. Will save us few operations.

**Comment by Osse** [comment]
@tatraian Hi, welcome back :)

Yes, what you describe is exactly what my original plan was. However there were conflicts. Many of these conflicts were due to upstream making changes similar to what the hunterization consisted of in the first place. Which is a good thing, I suppose. So I ended up looking at the diff between `v3.0.0-beta-2` and `v3.0.0-beta-2-hunter-2` and applying changes onto `v3.0.0` by hand making adaptations as needed.  In the end the diff between `v3.0.0` and `v3.0.0-hunter-1` is much smaller than the diff between `v3.0.0-beta-2` and `v3.0.0-beta-2-hunter-2`.

**Comment by tatraian** [comment]
@osse As I remember not only `CMake` files have been modified, I backported a small fix from protobuf to compile it with `clang`. But if they modified the `CMakelists.txt` and `install.cmake` then it can make rewrite easier than cherry picking...

@ruslo At the first release it is easier to make a merge to a "generic" hunter branch. But after the original project update, you have to merge into the same branch. In case of CMake files this will be hard after some releases (but you have experience in this).

**Comment by ruslo** [comment]
> In case of CMake files this will be hard after some releases

Why? If merge has conflicts then cherry-pick will have them too, but if there is no conflicts instead of doing several cherry-picks you can `git merge` only once. Hence merge looks preferable. Anyway you can do as you wish, result should be the same: 1. `git merge --ff-only` for master 2. minimal hunterization diff between hunter and master.

**Comment by tatraian** [comment]
You are right. That's seems easier, I prefer cherry pick because I see harder in "merge style" history what happened exactly.

**Pull request merged**
